"""
Gauge transformations for scalar cosmological perturbations.

# What "gauge" means here, and what it does not

A perturbed spacetime has no preferred coordinates. Splitting the metric into a
smooth background plus a perturbation requires choosing *which* coordinates count
as unperturbed, and different choices shuffle physical content between the metric
and the matter. That freedom is a **diffeomorphism**, xᵘ → xᵘ + ξᵘ, and fixing it
is what a cosmological gauge choice is.

This is a different redundancy from the one fixed by Coulomb (∇·A = 0) or Lorenz
(∂_μAᵘ = 0) gauge. Those fix the internal U(1) freedom of a *gauge field*,
A_μ → A_μ + ∂_μΛ. There is no Coulomb gauge for δg_μν. The gravitational analogue
of Lorenz gauge is **harmonic** (de Donder) gauge, □xᵘ = 0, which is a genuine
metric gauge -- it is what gravitational-wave calculations use -- but it is a
condition on the full metric, not one of the scalar gauges below.

# Why it matters numerically

A density contrast is *not* gauge invariant. δ_m in the Newtonian gauge and δ_m in
the synchronous gauge agree deep inside the horizon and disagree badly outside it.
The matter power spectrum is conventionally the synchronous/comoving one, and using
the Newtonian δ instead is 72% wrong at k = 5e-4 /Mpc while looking perfectly
healthy at k ≳ 0.01. This is not a subtlety you can defer.

# The transformation

Everything is generated by a single time shift T (the ξ⁰ of the diffeomorphism),
applied to the conformal-Newtonian solution the hierarchy produces:

    δ_X = δ_N + 3ℋ(1 + w) T
    θ_X = θ_N - k² T
    φ_X = φ_N + ℋ T

Each named gauge is just a choice of T:

| gauge            | condition            | T                          |
|------------------|----------------------|----------------------------|
| Newtonian        | (this is the origin) | 0                          |
| synchronous      | CDM at rest          | θ_c / k²                   |
| comoving         | total momentum = 0   | θ_tot / k²                 |
| uniform density  | δρ_tot = 0           | -δ_tot / (3ℋ(1+w_tot))     |
| spatially flat   | φ = 0                | -φ_N / ℋ                   |

Gauge-*invariant* combinations -- the comoving curvature ℛ and the uniform-density
curvature ζ -- are the same number in every gauge, and are what actually carries
physical meaning. See [`curvature_ℛ`](@ref).
"""

@enum Gauge Newtonian Synchronous Comoving UniformDensity SpatiallyFlat

"""
    gauge_shift(p, a, gauge)

The time shift T that takes the conformal-Newtonian solution into `gauge`.
Returns T in Mpc (the same units as conformal time).
"""
function gauge_shift(p::PerturbationSolution, a, gauge::Gauge)
    gauge === Newtonian && return 0.0

    c = p.cosmo
    k = p.k
    u = p.sol(log(a))
    ℋ_ = ℋ(c, a)

    if gauge === Synchronous
        # Synchronous gauge is defined by the CDM being at rest.
        return u[2] / k^2
    end

    ρ, ρθ, ρδ, ρw = _totals(p, u, a)

    if gauge === Comoving
        # Zero total momentum: θ_tot = Σ(1+w)ρθ / Σ(1+w)ρ
        return ρθ / (ρ + ρw) / k^2
    elseif gauge === UniformDensity
        # δρ_tot = 0.
        return -ρδ / (3 * ℋ_ * (ρ + ρw))
    elseif gauge === SpatiallyFlat
        return -u[5] / ℋ_
    end
    error("unknown gauge $gauge")
end

"Total ρ, Σ(1+w)ρθ, Σρδ, and ΣwρΣ over the perturbed species (units of ρ_c0)."
function _totals(p::PerturbationSolution, u, a)
    c = p.cosmo
    k = p.k
    L = _layout(p)

    ργ = Ω_γ(c) / a^4
    ρν = _Ω_or_zero(c, MasslessNeutrinos) / a^4
    ρb = Ω_b(c) / a^3
    ρc = Ω_c(c) / a^3

    δ_γ = u[L.iγ]
    θ_γ = 3k / 4 * u[L.iγ+1]
    δ_ν = u[L.iν]
    θ_ν = 3k / 4 * u[L.iν+1]

    ρ = ργ + ρν + ρb + ρc
    ρw = (ργ + ρν) / 3                              # Σ w ρ, w = 1/3 for radiation
    ρθ = (4 / 3) * ργ * θ_γ + (4 / 3) * ρν * θ_ν + ρb * u[4] + ρc * u[2]
    ρδ = ργ * δ_γ + ρν * δ_ν + ρb * u[3] + ρc * u[1]

    # Massive neutrinos contribute δρ, (ρ+P)θ, and their own ρ+P to the totals.
    if L.nmν > 0
        G = MassiveNuGrid(L.nq)
        mν = Tuple(get_all_species(c, MassiveNeutrinos))
        for (s, m) in enumerate(mν)
            am = m.y1 * a
            norm = m.Ω_rel / F_massless / a^4
            Iρ = Iδ = Iθ = IP = 0.0
            @inbounds for iq in 1:L.nq
                q = G.q[iq]
                ε = sqrt(q^2 + am^2)
                wf = G.w[iq] * G.f0[iq]
                Iρ += wf * q^2 * ε
                Iδ += wf * q^2 * ε * u[_imν(L, s, iq, 0)]
                Iθ += wf * q^3 * u[_imν(L, s, iq, 1)]
                IP += wf * q^2 * (q^2 / ε) / 3          # background pressure integral
            end
            ρ_s = norm * Iρ
            P_s = norm * IP
            ρ += ρ_s
            ρw += P_s
            ρδ += norm * Iδ
            ρθ += norm * k * Iθ
        end
    end
    (ρ, ρθ, ρδ, ρw)
end

"""
    δ_species(p, a, which, gauge)

Density contrast of one species in the requested gauge. `which` is one of
`:cdm`, `:baryon`, `:photon`, `:neutrino`, `:matter`.
"""
function δ_species(p::PerturbationSolution, a, which::Symbol, gauge::Gauge=Newtonian)
    c = p.cosmo
    L = _layout(p)
    u = p.sol(log(a))

    δ_N, w = if which === :cdm
        u[1], 0.0
    elseif which === :baryon
        u[3], 0.0
    elseif which === :photon
        u[L.iγ], 1 / 3
    elseif which === :neutrino
        u[L.iν], 1 / 3
    elseif which === :matter
        ρb, ρc = Ω_b(c), Ω_c(c)
        (ρc * u[1] + ρb * u[3]) / (ρc + ρb), 0.0
    else
        error("unknown species $which")
    end

    gauge === Newtonian && return δ_N
    T = gauge_shift(p, a, gauge)
    δ_N + 3 * ℋ(c, a) * (1 + w) * T
end

"""
    θ_species(p, a, which, gauge)

Velocity divergence of one species in the requested gauge.
"""
function θ_species(p::PerturbationSolution, a, which::Symbol, gauge::Gauge=Newtonian)
    c = p.cosmo
    L = _layout(p)
    u = p.sol(log(a))
    k = p.k

    θ_N = if which === :cdm
        u[2]
    elseif which === :baryon
        u[4]
    elseif which === :photon
        3k / 4 * u[L.iγ+1]
    elseif which === :neutrino
        3k / 4 * u[L.iν+1]
    elseif which === :matter
        ρb, ρc = Ω_b(c), Ω_c(c)
        (ρc * u[2] + ρb * u[4]) / (ρc + ρb)
    else
        error("unknown species $which")
    end

    gauge === Newtonian && return θ_N
    θ_N - k^2 * gauge_shift(p, a, gauge)
end

# --- Gauge-invariant quantities ---------------------------------------------

"""
    curvature_ℛ(p, a)

The **comoving curvature perturbation**,

    ℛ = φ + ℋ θ_tot / k²

Gauge invariant, and conserved on super-horizon scales for adiabatic
perturbations -- which is what lets inflation predict an initial condition at all,
since ℛ set during inflation survives untouched through reheating, through
equality, right up to horizon re-entry.

Cosmic normalises the initial conditions to ℛ = 1 per mode, so on large scales
this should return 1 at every time. That is not a tautology: ℛ is reconstructed
from the evolved φ and θ_tot, so it only comes out to 1 if the hierarchy and the
Einstein equations are consistent with each other.
"""
function curvature_ℛ(p::PerturbationSolution, a)
    u = p.sol(log(a))
    ρ, ρθ, _, ρw = _totals(p, u, a)
    θ_tot = ρθ / (ρ + ρw)
    u[5] + ℋ(p.cosmo, a) * θ_tot / p.k^2
end

"""
    curvature_ζ(p, a)

The **uniform-density curvature perturbation**,

    ζ = φ - δρ_tot / (3(ρ̄ + P̄))

Also gauge invariant, and equal to ℛ on super-horizon scales (they differ only by
terms of order (k/ℋ)²). ζ is the more natural variable when the equation of state
is changing, ℛ when it is not; both are conserved outside the horizon.
"""
function curvature_ζ(p::PerturbationSolution, a)
    u = p.sol(log(a))
    ρ, _, ρδ, ρw = _totals(p, u, a)
    u[5] - ρδ / (3 * (ρ + ρw))
end

"""
    bardeen_Φ(p, a), bardeen_Ψ(p, a)

The Bardeen potentials. These are gauge-invariant by construction, and they happen
to *coincide* with the metric potentials in the conformal Newtonian gauge -- which
is the deeper reason that gauge is so convenient: its variables are already the
gauge-invariant ones, so nothing is hiding in the coordinates.
"""
bardeen_Φ(p::PerturbationSolution, a) = Φ(p, a)
bardeen_Ψ(p::PerturbationSolution, a) = Ψ(p, a)
